@CognitoApiSample_HostAddress = http://localhost:5264
@Token = {{TOKEN}}

GET {{CognitoApiSample_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{Token}}

###

GET {{CognitoApiSample_HostAddress}}/weatherforecast/detailed
Accept: application/json
Authorization: Bearer {{Token}}

###

POST {{CognitoApiSample_HostAddress}}/weatherforecast
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
  "date": "2025-08-01",
  "temperatureC": 25,
  "summary": "Warm"
}

###
