@sqs_fifo_HostAddress = http://localhost:5298

GET {{sqs_fifo_HostAddress}}/weatherforecast?city=Brisbane
Accept: application/json

###

POST {{sqs_fifo_HostAddress}}/weatherforecast/
Accept: application/json
Content-Type: application/json

{
  "id": "b3b1a1e2-8c2e-4e2a-9c2e-1e2a9c2e1e3b",
  "city": "Brisbane",
  "details": {
    "date": "2025-09-24",
    "temperatureC": 16,
    "summary": "Warm"
  }
}

###